apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmessagequeues.example.org
spec:
  group: example.org
  names:
    kind: XMessageQueue
    plural: xmessagequeues
  claimNames:
    kind: MessageQueue
    plural: messagequeues
  versions:
    - name: v1alpha1
      served: true
      referenceable: true